version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5343:5342
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
    networks:
      - freecodecamp
networks:
  freecodecamp: